"#version 420 core\n"
"layout (location = 0) in vec3 v;"
"layout (location = 1) in vec2 v_tex_coord;"
""
"out vec2 tex_coords;"
""
"uniform mat4 model;"
"uniform mat4 view;"
"uniform mat4 proj;"
""
"void main()"
"{"
"    tex_coords = v_tex_coord;"
"    gl_Position = proj * view * model * vec4(v, 1.0);"
"}";