"#version 330 core\n"
"out vec4 color;"
""
"uniform sampler2D gPosition;"
"uniform sampler2D gView;"
"uniform sampler2D gNormal;"
"uniform sampler2D gDiffuse;"
"uniform sampler2D gSpecular;"
""
"in vec2 tex_coords;"
""
"struct PointLight"
"{"
"   vec3 pos;"
"   vec3 ambient;"
"   vec3 diffuse;"
"   vec3 specular;"
"   float coef_a0;"
"   float coef_a1;"
"   float coef_a2;"
"};"
"\n#define MAX_POINT_LIGHTS 100\n"
"uniform PointLight light[MAX_POINT_LIGHTS];"
""
"uniform int tot_light;"
""
"void main()"
"{"
"    vec3 frag_pos = texture(gPosition, tex_coords).rgb;"
"    vec3 view = texture(gView, tex_coords).rgb;"
"    vec3 norm = texture(gNormal, tex_coords).rgb;"
"    vec3 diffuse = texture(gDiffuse, tex_coords).rgb;"
"    vec3 specular = texture(gSpecular, tex_coords).rgb;"
"    float shininess = texture(gSpecular, tex_coords).a;"
"    vec3 light_color = vec3(texture(gView, tex_coords).a, texture(gNormal, tex_coords).a, texture(gDiffuse, tex_coords).a);"
""
"    for (int i = 0; i < tot_light; ++i)"
"    {"
"       if (light[i].coef_a0 == 0.f && light[i].coef_a1 == 0.f && light[i].coef_a2 == 0.f)"
"       {"
"           continue;"
"       }"
"       else"
"       {"
"           vec3 L = light[i].pos - frag_pos;"
"           float dist = length(L);"
"           L /= dist;"
"           vec3 R = reflect(-L, norm);"
""
"           float diff = max(dot(norm, L), 0.0);"
"           float spec = pow(max(dot(view, R), 0.0), shininess);"
""
"           float atten = 1.0f / (light[i].coef_a0 + light[i].coef_a1 * dist + light[i].coef_a2*dist*dist);"
""
"           vec3 a = light[i].ambient  * diffuse;"
"           vec3 d = light[i].diffuse  * diff * diffuse;"
"           vec3 s = light[i].specular * spec * specular;"
""
"           light_color += (a + d + s) * atten;"
"       }"
"    }"
"    color = vec4(light_color, 1.0f);"
"}"
